plugin {
    hyprbars {
        bar_height = 25

        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(ff4040), 10, 󰖭, hyprctl dispatch killactive
	windowrule = plugin:hyprbars:no_bar on, class:org.mozilla.firefox
    }
}

windowrule = plugin:hyprbars:bar_color rgb(ff0000) , class:org.mozilla.firefox
windowrule = plugin:hyprbars:nobar , class:org.mozilla.firefox
